/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze/{owner}/{repo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        /**
         * Analyze repository test specifications
         * @description Triggers or retrieves analysis for a GitHub repository.
         *     - Returns completed analysis if available
         *     - Queues new analysis if not found
         *     - Returns current status if analysis is in progress
         *
         */
        get: operations["analyzeRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/{owner}/{repo}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        /**
         * Get analysis status
         * @description Check the current status of repository analysis
         */
        get: operations["getAnalysisStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate GitHub OAuth login
         * @description Redirects to GitHub OAuth authorization page
         */
        get: operations["authLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub OAuth callback
         * @description Handles OAuth callback from GitHub and sets authentication cookie
         */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and clear authentication
         * @description Clears authentication cookies and revokes refresh token in database
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh authentication tokens
         * @description Exchanges a valid refresh token for a new access/refresh token pair.
         *     The old refresh token is invalidated (rotation).
         *     If a revoked token is used, the entire token family is invalidated (reuse detection).
         *
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info
         * @description Returns the currently authenticated user's information
         */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Development-only test login
         * @description Creates or retrieves a test user and issues authentication tokens.
         *     Only available when ENV != "production".
         *     WARNING: This endpoint is for development and E2E testing only.
         *
         */
        post: operations["authDevLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's bookmarked repositories
         * @description Returns list of repositories bookmarked by the authenticated user
         */
        get: operations["getUserBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/analyzed-repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's analyzed repositories
         * @description Returns paginated list of repositories analyzed by the authenticated user with ownership filtering
         */
        get: operations["getUserAnalyzedRepositories"];
        put?: never;
        /**
         * Add repository to user's analysis history
         * @description Adds a repository to the user's analysis history (dashboard).
         *     Useful when viewing analysis results from other users.
         *     UPSERT behavior - updates timestamp if already exists.
         *
         */
        post: operations["addUserAnalyzedRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recently analyzed repositories
         * @description Returns paginated list of analyzed repositories.
         *     Supports cursor-based pagination, sorting, and view filtering.
         *     - Default behavior (no params): Returns first 20 items sorted by recent analysis
         *     - Backward compatible: Existing clients work without changes
         *     - Authentication: Optional for view=community/all with ownership=all. Required for view=my or ownership=mine/organization.
         *
         */
        get: operations["getRecentRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository statistics
         * @description Returns aggregate statistics for user's repositories
         */
        get: operations["getRepositoryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{owner}/{repo}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bookmark a repository
         * @description Add repository to user's bookmarks
         */
        post: operations["addBookmark"];
        /**
         * Remove bookmark
         * @description Remove repository from user's bookmarks
         */
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{owner}/{repo}/update-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        /**
         * Check repository update status
         * @description Checks if repository has new commits since last analysis.
         *     Uses git ls-remote to check latest commit SHA.
         *
         */
        get: operations["getUpdateStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{owner}/{repo}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger repository re-analysis
         * @description Queues a new analysis job for the repository.
         *     Returns job status that can be polled via /api/analyze/{owner}/{repo}/status
         *
         */
        post: operations["reanalyzeRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's GitHub repositories
         * @description Returns all repositories accessible by the authenticated user from GitHub
         */
        get: operations["getUserGitHubRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/github/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's GitHub organizations
         * @description Returns all organizations the authenticated user belongs to
         */
        get: operations["getUserGitHubOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/github/organizations/{org}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub organization login name
                 * @example facebook
                 */
                org: string;
            };
            cookie?: never;
        };
        /**
         * Get organization's repositories
         * @description Returns all repositories in the specified organization
         */
        get: operations["getOrganizationRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/github-app/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's GitHub App installations
         * @description Returns list of GitHub App installations accessible to the authenticated user
         */
        get: operations["getUserGitHubAppInstallations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/github-app/install-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get GitHub App installation URL
         * @description Returns the URL to install the GitHub App on a GitHub account
         */
        get: operations["getGitHubAppInstallUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/github-app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle GitHub App webhook events
         * @description Receives and processes webhook events from GitHub App.
         *     Handles installation, installation_repositories, and other GitHub App events.
         *     Webhook signature is verified using HMAC-SHA256.
         *
         */
        post: operations["handleGitHubAppWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalysisResponse: components["schemas"]["CompletedResponse"] | components["schemas"]["AnalyzingResponse"] | components["schemas"]["QueuedResponse"] | components["schemas"]["FailedResponse"];
        CompletedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "completed";
            data: components["schemas"]["AnalysisResult"];
        };
        AnalyzingResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "analyzing";
        };
        QueuedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "queued";
        };
        FailedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
            /** @description Error message describing the failure */
            error: string;
        };
        AnalysisResult: {
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of analysis completion
             * @example 2024-01-15T10:30:00Z
             */
            analyzedAt: string;
            /**
             * @description Branch name that was analyzed
             * @example main
             */
            branchName?: string;
            /**
             * @description Git commit SHA that was analyzed
             * @example abc123def456
             */
            commitSha: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the commit
             * @example 2024-01-14T09:00:00Z
             */
            committedAt?: string;
            /** @description Whether this analysis is in the current user's dashboard history */
            isInMyHistory?: boolean;
            /**
             * @description Repository owner
             * @example facebook
             */
            owner: string;
            /**
             * @description Repository name
             * @example react
             */
            repo: string;
            suites: components["schemas"]["TestSuite"][];
            summary: components["schemas"]["Summary"];
        };
        TestSuite: {
            /**
             * @description Path to the test file relative to repository root
             * @example src/__tests__/App.test.tsx
             */
            filePath: string;
            framework: components["schemas"]["Framework"];
            /**
             * @description Name of the test suite (describe block name)
             * @example UserService
             */
            suiteName: string;
            tests: components["schemas"]["TestCase"][];
        };
        TestCase: {
            /** @description Path to the test file */
            filePath: string;
            framework: components["schemas"]["Framework"];
            /** @description Line number where the test is defined */
            line: number;
            /** @description Test modifier (e.g., only, skip) */
            modifier?: string;
            /** @description Test case name */
            name: string;
            status: components["schemas"]["TestStatus"];
        };
        /**
         * @description Test status indicator:
         *     - active: Normal test that will run
         *     - focused: Test marked to run exclusively (e.g., it.only)
         *     - skipped: Test marked to be skipped (e.g., it.skip)
         *     - todo: Placeholder test to be implemented
         *     - xfail: Expected to fail (pytest xfail)
         *
         * @enum {string}
         */
        TestStatus: "active" | "focused" | "skipped" | "todo" | "xfail";
        /**
         * @description Testing framework identifier
         * @example vitest
         */
        Framework: string;
        Summary: {
            /** @description Number of active tests */
            active: number;
            /** @description Number of focused tests */
            focused: number;
            frameworks: components["schemas"]["FrameworkSummary"][];
            /** @description Number of skipped tests */
            skipped: number;
            /** @description Number of todo tests */
            todo: number;
            /** @description Total number of tests */
            total: number;
            /** @description Number of xfail tests */
            xfail: number;
        };
        FrameworkSummary: {
            active: number;
            focused: number;
            framework: components["schemas"]["Framework"];
            skipped: number;
            todo: number;
            total: number;
            xfail: number;
        };
        ProblemDetail: {
            /**
             * Format: uri
             * @description URI identifying the problem type
             * @default about:blank
             */
            type: string;
            /** @description Human-readable summary */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Human-readable explanation specific to this occurrence */
            detail: string;
            /** @description URI reference identifying the specific occurrence */
            instance?: string;
            rateLimit?: components["schemas"]["RateLimitInfo"];
        };
        RateLimitInfo: {
            /** @description Maximum requests allowed per time window */
            limit: number;
            /** @description Remaining requests in current window */
            remaining: number;
            /**
             * Format: int64
             * @description Unix timestamp when the rate limit resets
             */
            resetAt: number;
        };
        LoginResponse: {
            /**
             * Format: uri
             * @description GitHub OAuth authorization URL to redirect user
             */
            authUrl: string;
        };
        UserInfo: {
            /** @description Internal user ID */
            id: string;
            /** @description GitHub username */
            login: string;
            /**
             * Format: uri
             * @description GitHub avatar URL
             */
            avatarUrl: string;
            /** @description GitHub display name (optional) */
            name?: string;
        };
        LogoutResponse: {
            /** @description Logout operation result */
            success: boolean;
        };
        RefreshResponse: {
            /** @description Token refresh operation result */
            success: boolean;
        };
        DevLoginRequest: {
            /** @description Optional user ID to login as (uses default test user if not provided) */
            userId?: string;
            /** @description Optional username for test user (default is "test-user") */
            username?: string;
        };
        DevLoginResponse: {
            success: boolean;
            user: components["schemas"]["UserInfo"];
        };
        BookmarkedRepositoriesResponse: {
            /** @description Bookmarked repositories */
            data: components["schemas"]["RepositoryCard"][];
        };
        PaginatedRepositoriesResponse: {
            /** @description Repositories in the current page */
            data: components["schemas"]["RepositoryCard"][];
            /** @description Cursor for fetching the next page (null if no more pages) */
            nextCursor?: string | null;
            /** @description Whether more pages are available */
            hasNext: boolean;
        };
        /**
         * @description Field to sort repositories by:
         *     - name: Repository name (alphabetical)
         *     - recent: Analysis timestamp (most recent first)
         *     - tests: Test count (highest first)
         *
         * @default recent
         * @enum {string}
         */
        SortByParam: "name" | "recent" | "tests";
        /**
         * @description Sort direction:
         *     - asc: Ascending order
         *     - desc: Descending order
         *     Defaults depend on sortBy (desc for recent/tests, asc for name)
         *
         * @enum {string}
         */
        SortOrderParam: "asc" | "desc";
        /**
         * @description Filter repositories by analyzer (who analyzed):
         *     - all: All analyzed repositories
         *     - my: Only repositories analyzed by the current user
         *     - community: Only repositories analyzed by other users
         *
         * @default all
         * @enum {string}
         */
        ViewFilterParam: "all" | "my" | "community";
        /**
         * @description Filter repositories by ownership type:
         *     - all: All analyzed repositories (personal and organization)
         *     - mine: Only repositories owned by the current user
         *     - organization: Only repositories owned by organizations the user is a member of
         *     - others: Only repositories owned by other users (not mine, not organization)
         *
         * @default all
         * @enum {string}
         */
        OwnershipFilterParam: "all" | "mine" | "organization" | "others";
        RepositoryStatsResponse: {
            /**
             * @description Total number of analyzed repositories for the user
             * @example 12
             */
            totalRepositories: number;
            /**
             * @description Total number of tests across all repositories
             * @example 1543
             */
            totalTests: number;
        };
        UserAnalyzedRepositoriesResponse: {
            /** @description Analyzed repositories in the current page */
            data: components["schemas"]["RepositoryCard"][];
            /** @description Cursor for fetching the next page (null if no more pages) */
            nextCursor?: string | null;
            /** @description Whether more pages are available */
            hasNext: boolean;
        };
        AddAnalyzedRepositoryRequest: {
            /**
             * @description GitHub repository owner
             * @example facebook
             */
            owner: string;
            /**
             * @description GitHub repository name
             * @example react
             */
            repo: string;
        };
        AddAnalyzedRepositoryResponse: {
            /** @description Analysis ID added to user's history */
            analysisId: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the history was updated
             */
            updatedAt: string;
        };
        RepositoryCard: {
            /**
             * @description Repository ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Repository owner (user or organization)
             * @example facebook
             */
            owner: string;
            /**
             * @description Repository name
             * @example react
             */
            name: string;
            /**
             * @description Full repository name in owner/name format
             * @example facebook/react
             */
            fullName: string;
            /** @description Whether the repository is bookmarked by the user */
            isBookmarked: boolean;
            /** @description Whether the repository was analyzed by the current user */
            isAnalyzedByMe: boolean;
            latestAnalysis?: components["schemas"]["AnalysisSummary"];
            updateStatus: components["schemas"]["UpdateStatus"];
        };
        AnalysisSummary: {
            /**
             * @description Total number of tests in the latest analysis
             * @example 312
             */
            testCount: number;
            /**
             * @description Change in test count compared to previous analysis
             * @example 5
             */
            change: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when analysis was completed
             * @example 2024-01-15T10:30:00Z
             */
            analyzedAt: string;
            /**
             * @description Git commit SHA that was analyzed
             * @example abc123def456
             */
            commitSha: string;
            testSummary?: components["schemas"]["TestStatusSummary"];
        };
        TestStatusSummary: {
            /**
             * @description Number of active tests
             * @example 280
             */
            active: number;
            /**
             * @description Number of focused tests (.only())
             * @example 2
             */
            focused: number;
            /**
             * @description Number of skipped tests (.skip())
             * @example 15
             */
            skipped: number;
            /**
             * @description Number of todo tests
             * @example 10
             */
            todo: number;
            /**
             * @description Number of expected-to-fail tests
             * @example 5
             */
            xfail: number;
        };
        /**
         * @description Repository update status:
         *     - up-to-date: Latest analysis is current with HEAD
         *     - new-commits: New commits available since last analysis
         *     - unknown: Unable to determine status
         *
         * @enum {string}
         */
        UpdateStatus: "up-to-date" | "new-commits" | "unknown";
        UpdateStatusResponse: {
            status: components["schemas"]["UpdateStatus"];
            /**
             * @description Latest commit SHA from remote
             * @example def789abc123
             */
            latestCommitSha?: string;
            /**
             * @description Commit SHA from last analysis
             * @example abc123def456
             */
            analyzedCommitSha?: string;
        };
        BookmarkResponse: {
            /** @description Operation success status */
            success: boolean;
            /** @description Current bookmark status after the operation */
            isBookmarked: boolean;
        };
        GitHubRepositoriesResponse: {
            /** @description List of GitHub repositories */
            data: components["schemas"]["GitHubRepository"][];
        };
        GitHubOrganizationsResponse: {
            /** @description List of GitHub organizations */
            data: components["schemas"]["GitHubOrganization"][];
        };
        GitHubRepository: {
            /**
             * Format: int64
             * @description GitHub repository ID
             * @example 10270250
             */
            id: number;
            /**
             * @description Repository name
             * @example react
             */
            name: string;
            /**
             * @description Full repository name in owner/name format
             * @example facebook/react
             */
            fullName: string;
            /**
             * @description Repository owner login
             * @example facebook
             */
            owner: string;
            /** @description Repository description */
            description?: string;
            /**
             * @description Default branch name
             * @example main
             */
            defaultBranch: string;
            /** @description Whether the repository is private */
            isPrivate: boolean;
            /**
             * Format: date-time
             * @description Last push timestamp
             */
            pushedAt?: string;
        };
        GitHubOrganization: {
            /**
             * Format: int64
             * @description GitHub organization ID
             * @example 69631
             */
            id: number;
            /**
             * @description Organization login name
             * @example facebook
             */
            login: string;
            /**
             * Format: uri
             * @description Organization avatar URL
             */
            avatarUrl?: string;
            /** @description Organization description */
            description?: string;
            accessStatus: components["schemas"]["OrganizationAccessStatus"];
        };
        /**
         * @description Organization repository access status.
         *     - accessible: GitHub App installed, can access organization repositories
         *     - restricted: No GitHub App installation, cannot access organization repositories
         *     - pending: GitHub App installation is suspended
         *
         * @enum {string}
         */
        OrganizationAccessStatus: "accessible" | "restricted" | "pending";
        GitHubAppInstallationsResponse: {
            /** @description List of GitHub App installations */
            data: components["schemas"]["GitHubAppInstallation"][];
        };
        GitHubAppInstallation: {
            /** @description Internal installation record ID */
            id: string;
            /**
             * Format: int64
             * @description GitHub installation ID
             */
            installationId: number;
            /**
             * @description Type of GitHub account
             * @enum {string}
             */
            accountType: "organization" | "user";
            /**
             * Format: int64
             * @description GitHub account ID
             */
            accountId: number;
            /** @description GitHub account login name */
            accountLogin: string;
            /**
             * Format: uri
             * @description GitHub account avatar URL
             */
            accountAvatarUrl?: string;
            /**
             * Format: date-time
             * @description When the installation was created
             */
            createdAt: string;
            /** @description Whether the installation is suspended */
            isSuspended: boolean;
        };
        GitHubAppInstallUrlResponse: {
            /**
             * Format: uri
             * @description URL to install the GitHub App
             */
            installUrl: string;
        };
        /** @description GitHub webhook payload. The structure varies by event type.
         *     This schema represents the common fields; specific event handling uses raw JSON.
         *      */
        GitHubWebhookPayload: {
            /** @description The action that was performed (e.g., created, deleted, added, removed) */
            action?: string;
            installation?: components["schemas"]["WebhookInstallation"];
            sender?: components["schemas"]["WebhookSender"];
            /** @description Repositories affected by the event (for installation_repositories events) */
            repositories?: components["schemas"]["WebhookRepository"][];
            /** @description Repositories added (for installation_repositories.added events) */
            repositories_added?: components["schemas"]["WebhookRepository"][];
            /** @description Repositories removed (for installation_repositories.removed events) */
            repositories_removed?: components["schemas"]["WebhookRepository"][];
        };
        WebhookInstallation: {
            /**
             * Format: int64
             * @description GitHub App installation ID
             */
            id: number;
            account: components["schemas"]["WebhookAccount"];
            /**
             * Format: date-time
             * @description When the installation was suspended
             */
            suspended_at?: string | null;
        };
        WebhookAccount: {
            /**
             * Format: int64
             * @description GitHub account ID
             */
            id: number;
            /** @description Account login name */
            login: string;
            /**
             * @description Account type
             * @enum {string}
             */
            type: "User" | "Organization";
            /**
             * Format: uri
             * @description Account avatar URL
             */
            avatar_url?: string;
        };
        WebhookSender: {
            /**
             * Format: int64
             * @description GitHub user ID of the sender
             */
            id: number;
            /** @description GitHub username of the sender */
            login: string;
        };
        WebhookRepository: {
            /**
             * Format: int64
             * @description GitHub repository ID
             */
            id: number;
            /** @description Repository name */
            name: string;
            /** @description Full repository name (owner/repo) */
            full_name: string;
            /** @description Whether the repository is private */
            private?: boolean;
        };
        WebhookResponse: {
            /** @description Whether the webhook was processed successfully */
            success: boolean;
            /** @description Optional message about the processing result */
            message?: string;
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Access forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /**
         * @description GitHub repository owner (user or organization)
         * @example facebook
         */
        Owner: string;
        /**
         * @description GitHub repository name
         * @example react
         */
        Repo: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyzeRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedResponse"];
                };
            };
            /** @description Analysis accepted and processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedResponse"] | components["schemas"]["AnalyzingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getAnalysisStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis status retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth authorization URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    authCallback: {
        parameters: {
            query: {
                /** @description OAuth authorization code from GitHub */
                code: string;
                /** @description OAuth state for CSRF protection */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to frontend after successful authentication */
            302: {
                headers: {
                    /** @description Frontend URL to redirect to */
                    Location?: string;
                    /** @description HTTP-only authentication cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens refreshed successfully */
            200: {
                headers: {
                    /** @description New access and refresh tokens as HTTP-only cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    authDevLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    /** @description Authentication cookies (auth_token, refresh_token) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevLoginResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserBookmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarked repositories retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkedRepositoriesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserAnalyzedRepositories: {
        parameters: {
            query?: {
                /** @description Pagination cursor for next page (opaque string from previous response) */
                cursor?: string;
                /** @description Maximum number of repositories to return per page */
                limit?: number;
                /** @description Filter repositories by ownership:
                 *     - all: All analyzed repositories (personal and organization)
                 *     - mine: Only repositories owned by the user
                 *     - organization: Only repositories owned by organizations
                 *      */
                ownership?: "all" | "mine" | "organization";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analyzed repositories retrieved with pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAnalyzedRepositoriesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    addUserAnalyzedRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAnalyzedRepositoryRequest"];
            };
        };
        responses: {
            /** @description Repository added to history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddAnalyzedRepositoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getRecentRepositories: {
        parameters: {
            query?: {
                /** @description Pagination cursor for next page (opaque string from previous response) */
                cursor?: string;
                /** @description Maximum number of repositories to return per page */
                limit?: number;
                /** @description Field to sort by (default is recent) */
                sortBy?: components["schemas"]["SortByParam"];
                /** @description Sort direction (default depends on sortBy - desc for recent/tests, asc for name) */
                sortOrder?: components["schemas"]["SortOrderParam"];
                /** @description Filter repositories by analyzer (who analyzed the repository) */
                view?: components["schemas"]["ViewFilterParam"];
                /** @description Filter repositories by ownership type */
                ownership?: components["schemas"]["OwnershipFilterParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories retrieved with pagination info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRepositoriesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getRepositoryStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryStatsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark added successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark removed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getUpdateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update status retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reanalyzeRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Re-analysis queued successfully */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedResponse"] | components["schemas"]["AnalyzingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserGitHubRepositories: {
        parameters: {
            query?: {
                /** @description Force refresh from GitHub API, bypassing cache */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub repositories retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoriesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserGitHubOrganizations: {
        parameters: {
            query?: {
                /** @description Force refresh from GitHub API, bypassing cache */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub organizations retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubOrganizationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getOrganizationRepositories: {
        parameters: {
            query?: {
                /** @description Force refresh from GitHub API, bypassing cache */
                refresh?: boolean;
            };
            header?: never;
            path: {
                /**
                 * @description GitHub organization login name
                 * @example facebook
                 */
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization repositories retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoriesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserGitHubAppInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub App installations retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubAppInstallationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getGitHubAppInstallUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation URL generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubAppInstallUrlResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    handleGitHubAppWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description GitHub event type (e.g., installation, installation_repositories) */
                "X-GitHub-Event": string;
                /** @description HMAC-SHA256 signature for payload verification */
                "X-Hub-Signature-256": string;
                /** @description Unique delivery ID for this webhook event */
                "X-GitHub-Delivery": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubWebhookPayload"];
            };
        };
        responses: {
            /** @description Webhook processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid webhook signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
