// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for TestStatus.
const (
	Active  TestStatus = "active"
	Focused TestStatus = "focused"
	Skipped TestStatus = "skipped"
	Todo    TestStatus = "todo"
	Xfail   TestStatus = "xfail"
)

// AnalysisResponse defines model for AnalysisResponse.
type AnalysisResponse struct {
	union json.RawMessage
}

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	// AnalyzedAt ISO 8601 timestamp of analysis completion
	AnalyzedAt time.Time `json:"analyzedAt"`

	// CommitSHA Git commit SHA that was analyzed
	CommitSHA string `json:"commitSha"`

	// Owner Repository owner
	Owner string `json:"owner"`

	// Repo Repository name
	Repo    string      `json:"repo"`
	Suites  []TestSuite `json:"suites"`
	Summary Summary     `json:"summary"`
}

// AnalyzingResponse defines model for AnalyzingResponse.
type AnalyzingResponse struct {
	Status string `json:"status"`
}

// CompletedResponse defines model for CompletedResponse.
type CompletedResponse struct {
	Data   AnalysisResult `json:"data"`
	Status string         `json:"status"`
}

// FailedResponse defines model for FailedResponse.
type FailedResponse struct {
	// Error Error message describing the failure
	Error  string `json:"error"`
	Status string `json:"status"`
}

// Framework Testing framework identifier
type Framework = string

// FrameworkSummary defines model for FrameworkSummary.
type FrameworkSummary struct {
	Active  int `json:"active"`
	Focused int `json:"focused"`

	// Framework Testing framework identifier
	Framework Framework `json:"framework"`
	Skipped   int       `json:"skipped"`
	Todo      int       `json:"todo"`
	Total     int       `json:"total"`
	Xfail     int       `json:"xfail"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AuthURL GitHub OAuth authorization URL to redirect user
	AuthURL string `json:"authUrl"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	// Success Logout operation result
	Success bool `json:"success"`
}

// ProblemDetail defines model for ProblemDetail.
type ProblemDetail struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail string `json:"detail"`

	// Instance URI reference identifying the specific occurrence
	Instance  *string        `json:"instance,omitempty"`
	RateLimit *RateLimitInfo `json:"rateLimit,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Human-readable summary
	Title string `json:"title"`

	// Type URI identifying the problem type
	Type *string `json:"type,omitempty"`
}

// QueuedResponse defines model for QueuedResponse.
type QueuedResponse struct {
	Status string `json:"status"`
}

// RateLimitInfo defines model for RateLimitInfo.
type RateLimitInfo struct {
	// Limit Maximum requests allowed per time window
	Limit int `json:"limit"`

	// Remaining Remaining requests in current window
	Remaining int `json:"remaining"`

	// ResetAt Unix timestamp when the rate limit resets
	ResetAt int64 `json:"resetAt"`
}

// Summary defines model for Summary.
type Summary struct {
	// Active Number of active tests
	Active int `json:"active"`

	// Focused Number of focused tests
	Focused    int                `json:"focused"`
	Frameworks []FrameworkSummary `json:"frameworks"`

	// Skipped Number of skipped tests
	Skipped int `json:"skipped"`

	// Todo Number of todo tests
	Todo int `json:"todo"`

	// Total Total number of tests
	Total int `json:"total"`

	// Xfail Number of xfail tests
	Xfail int `json:"xfail"`
}

// TestCase defines model for TestCase.
type TestCase struct {
	// FilePath Path to the test file
	FilePath string `json:"filePath"`

	// Framework Testing framework identifier
	Framework Framework `json:"framework"`

	// Line Line number where the test is defined
	Line int `json:"line"`

	// Modifier Test modifier (e.g., only, skip)
	Modifier *string `json:"modifier,omitempty"`

	// Name Test case name
	Name string `json:"name"`

	// Status Test status indicator:
	// - active: Normal test that will run
	// - focused: Test marked to run exclusively (e.g., it.only)
	// - skipped: Test marked to be skipped (e.g., it.skip)
	// - todo: Placeholder test to be implemented
	// - xfail: Expected to fail (pytest xfail)
	Status TestStatus `json:"status"`
}

// TestStatus Test status indicator:
// - active: Normal test that will run
// - focused: Test marked to run exclusively (e.g., it.only)
// - skipped: Test marked to be skipped (e.g., it.skip)
// - todo: Placeholder test to be implemented
// - xfail: Expected to fail (pytest xfail)
type TestStatus string

// TestSuite defines model for TestSuite.
type TestSuite struct {
	// FilePath Path to the test file relative to repository root
	FilePath string `json:"filePath"`

	// Framework Testing framework identifier
	Framework Framework  `json:"framework"`
	Tests     []TestCase `json:"tests"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	// AvatarURL GitHub avatar URL
	AvatarURL string `json:"avatarUrl"`

	// ID Internal user ID
	ID string `json:"id"`

	// Login GitHub username
	Login string `json:"login"`

	// Name GitHub display name (optional)
	Name *string `json:"name,omitempty"`
}

// Owner defines model for Owner.
type Owner = string

// Repo defines model for Repo.
type Repo = string

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetail

// InternalError defines model for InternalError.
type InternalError = ProblemDetail

// NotFound defines model for NotFound.
type NotFound = ProblemDetail

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetail

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	// Code OAuth authorization code from GitHub
	Code string `form:"code" json:"code"`

	// State OAuth state for CSRF protection
	State string `form:"state" json:"state"`
}

// AsCompletedResponse returns the union data inside the AnalysisResponse as a CompletedResponse
func (t AnalysisResponse) AsCompletedResponse() (CompletedResponse, error) {
	var body CompletedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCompletedResponse overwrites any union data inside the AnalysisResponse as the provided CompletedResponse
func (t *AnalysisResponse) FromCompletedResponse(v CompletedResponse) error {
	v.Status = "completed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCompletedResponse performs a merge with any union data inside the AnalysisResponse, using the provided CompletedResponse
func (t *AnalysisResponse) MergeCompletedResponse(v CompletedResponse) error {
	v.Status = "completed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnalyzingResponse returns the union data inside the AnalysisResponse as a AnalyzingResponse
func (t AnalysisResponse) AsAnalyzingResponse() (AnalyzingResponse, error) {
	var body AnalyzingResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnalyzingResponse overwrites any union data inside the AnalysisResponse as the provided AnalyzingResponse
func (t *AnalysisResponse) FromAnalyzingResponse(v AnalyzingResponse) error {
	v.Status = "analyzing"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnalyzingResponse performs a merge with any union data inside the AnalysisResponse, using the provided AnalyzingResponse
func (t *AnalysisResponse) MergeAnalyzingResponse(v AnalyzingResponse) error {
	v.Status = "analyzing"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueuedResponse returns the union data inside the AnalysisResponse as a QueuedResponse
func (t AnalysisResponse) AsQueuedResponse() (QueuedResponse, error) {
	var body QueuedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueuedResponse overwrites any union data inside the AnalysisResponse as the provided QueuedResponse
func (t *AnalysisResponse) FromQueuedResponse(v QueuedResponse) error {
	v.Status = "queued"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueuedResponse performs a merge with any union data inside the AnalysisResponse, using the provided QueuedResponse
func (t *AnalysisResponse) MergeQueuedResponse(v QueuedResponse) error {
	v.Status = "queued"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedResponse returns the union data inside the AnalysisResponse as a FailedResponse
func (t AnalysisResponse) AsFailedResponse() (FailedResponse, error) {
	var body FailedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedResponse overwrites any union data inside the AnalysisResponse as the provided FailedResponse
func (t *AnalysisResponse) FromFailedResponse(v FailedResponse) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedResponse performs a merge with any union data inside the AnalysisResponse, using the provided FailedResponse
func (t *AnalysisResponse) MergeFailedResponse(v FailedResponse) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnalysisResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AnalysisResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "analyzing":
		return t.AsAnalyzingResponse()
	case "completed":
		return t.AsCompletedResponse()
	case "failed":
		return t.AsFailedResponse()
	case "queued":
		return t.AsQueuedResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AnalysisResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnalysisResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Analyze repository test specifications
	// (GET /api/analyze/{owner}/{repo})
	AnalyzeRepository(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo)
	// Get analysis status
	// (GET /api/analyze/{owner}/{repo}/status)
	GetAnalysisStatus(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo)
	// GitHub OAuth callback
	// (GET /api/auth/callback)
	AuthCallback(w http.ResponseWriter, r *http.Request, params AuthCallbackParams)
	// Initiate GitHub OAuth login
	// (GET /api/auth/login)
	AuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout and clear authentication
	// (POST /api/auth/logout)
	AuthLogout(w http.ResponseWriter, r *http.Request)
	// Get current user info
	// (GET /api/auth/me)
	AuthMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Analyze repository test specifications
// (GET /api/analyze/{owner}/{repo})
func (_ Unimplemented) AnalyzeRepository(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get analysis status
// (GET /api/analyze/{owner}/{repo}/status)
func (_ Unimplemented) GetAnalysisStatus(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GitHub OAuth callback
// (GET /api/auth/callback)
func (_ Unimplemented) AuthCallback(w http.ResponseWriter, r *http.Request, params AuthCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate GitHub OAuth login
// (GET /api/auth/login)
func (_ Unimplemented) AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and clear authentication
// (POST /api/auth/logout)
func (_ Unimplemented) AuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user info
// (GET /api/auth/me)
func (_ Unimplemented) AuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AnalyzeRepository operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeRepository(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeRepository(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalysisStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysisStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "owner" -------------
	var owner Owner

	err = runtime.BindStyledParameterWithOptions("simple", "owner", chi.URLParam(r, "owner"), &owner, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Path parameter "repo" -------------
	var repo Repo

	err = runtime.BindStyledParameterWithOptions("simple", "repo", chi.URLParam(r, "repo"), &repo, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysisStatus(w, r, owner, repo)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthCallback operation middleware
func (siw *ServerInterfaceWrapper) AuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) AuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthMe operation middleware
func (siw *ServerInterfaceWrapper) AuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/analyze/{owner}/{repo}", wrapper.AnalyzeRepository)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/analyze/{owner}/{repo}/status", wrapper.GetAnalysisStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/callback", wrapper.AuthCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/login", wrapper.AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.AuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/me", wrapper.AuthMe)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse ProblemDetail

type InternalErrorApplicationProblemPlusJSONResponse ProblemDetail

type NotFoundApplicationProblemPlusJSONResponse ProblemDetail

type UnauthorizedApplicationProblemPlusJSONResponse ProblemDetail

type AnalyzeRepositoryRequestObject struct {
	Owner Owner `json:"owner"`
	Repo  Repo  `json:"repo"`
}

type AnalyzeRepositoryResponseObject interface {
	VisitAnalyzeRepositoryResponse(w http.ResponseWriter) error
}

type AnalyzeRepository200JSONResponse CompletedResponse

func (response AnalyzeRepository200JSONResponse) VisitAnalyzeRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AnalyzeRepository202JSONResponse struct {
	union json.RawMessage
}

func (response AnalyzeRepository202JSONResponse) VisitAnalyzeRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response.union)
}

type AnalyzeRepository400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response AnalyzeRepository400ApplicationProblemPlusJSONResponse) VisitAnalyzeRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AnalyzeRepository500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response AnalyzeRepository500ApplicationProblemPlusJSONResponse) VisitAnalyzeRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAnalysisStatusRequestObject struct {
	Owner Owner `json:"owner"`
	Repo  Repo  `json:"repo"`
}

type GetAnalysisStatusResponseObject interface {
	VisitGetAnalysisStatusResponse(w http.ResponseWriter) error
}

type GetAnalysisStatus200JSONResponse AnalysisResponse

func (response GetAnalysisStatus200JSONResponse) VisitGetAnalysisStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnalysisStatus400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetAnalysisStatus400ApplicationProblemPlusJSONResponse) VisitGetAnalysisStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAnalysisStatus404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetAnalysisStatus404ApplicationProblemPlusJSONResponse) VisitGetAnalysisStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAnalysisStatus500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetAnalysisStatus500ApplicationProblemPlusJSONResponse) VisitGetAnalysisStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthCallbackRequestObject struct {
	Params AuthCallbackParams
}

type AuthCallbackResponseObject interface {
	VisitAuthCallbackResponse(w http.ResponseWriter) error
}

type AuthCallback302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type AuthCallback302Response struct {
	Headers AuthCallback302ResponseHeaders
}

func (response AuthCallback302Response) VisitAuthCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type AuthCallback400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response AuthCallback400ApplicationProblemPlusJSONResponse) VisitAuthCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthCallback500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response AuthCallback500ApplicationProblemPlusJSONResponse) VisitAuthCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthLoginRequestObject struct {
}

type AuthLoginResponseObject interface {
	VisitAuthLoginResponse(w http.ResponseWriter) error
}

type AuthLogin200JSONResponse LoginResponse

func (response AuthLogin200JSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthLogin500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response AuthLogin500ApplicationProblemPlusJSONResponse) VisitAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthLogoutRequestObject struct {
}

type AuthLogoutResponseObject interface {
	VisitAuthLogoutResponse(w http.ResponseWriter) error
}

type AuthLogout200JSONResponse LogoutResponse

func (response AuthLogout200JSONResponse) VisitAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthLogout500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response AuthLogout500ApplicationProblemPlusJSONResponse) VisitAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthMeRequestObject struct {
}

type AuthMeResponseObject interface {
	VisitAuthMeResponse(w http.ResponseWriter) error
}

type AuthMe200JSONResponse UserInfo

func (response AuthMe200JSONResponse) VisitAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response AuthMe401ApplicationProblemPlusJSONResponse) VisitAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthMe500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response AuthMe500ApplicationProblemPlusJSONResponse) VisitAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Analyze repository test specifications
	// (GET /api/analyze/{owner}/{repo})
	AnalyzeRepository(ctx context.Context, request AnalyzeRepositoryRequestObject) (AnalyzeRepositoryResponseObject, error)
	// Get analysis status
	// (GET /api/analyze/{owner}/{repo}/status)
	GetAnalysisStatus(ctx context.Context, request GetAnalysisStatusRequestObject) (GetAnalysisStatusResponseObject, error)
	// GitHub OAuth callback
	// (GET /api/auth/callback)
	AuthCallback(ctx context.Context, request AuthCallbackRequestObject) (AuthCallbackResponseObject, error)
	// Initiate GitHub OAuth login
	// (GET /api/auth/login)
	AuthLogin(ctx context.Context, request AuthLoginRequestObject) (AuthLoginResponseObject, error)
	// Logout and clear authentication
	// (POST /api/auth/logout)
	AuthLogout(ctx context.Context, request AuthLogoutRequestObject) (AuthLogoutResponseObject, error)
	// Get current user info
	// (GET /api/auth/me)
	AuthMe(ctx context.Context, request AuthMeRequestObject) (AuthMeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AnalyzeRepository operation middleware
func (sh *strictHandler) AnalyzeRepository(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo) {
	var request AnalyzeRepositoryRequestObject

	request.Owner = owner
	request.Repo = repo

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AnalyzeRepository(ctx, request.(AnalyzeRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AnalyzeRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AnalyzeRepositoryResponseObject); ok {
		if err := validResponse.VisitAnalyzeRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAnalysisStatus operation middleware
func (sh *strictHandler) GetAnalysisStatus(w http.ResponseWriter, r *http.Request, owner Owner, repo Repo) {
	var request GetAnalysisStatusRequestObject

	request.Owner = owner
	request.Repo = repo

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnalysisStatus(ctx, request.(GetAnalysisStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnalysisStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAnalysisStatusResponseObject); ok {
		if err := validResponse.VisitGetAnalysisStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthCallback operation middleware
func (sh *strictHandler) AuthCallback(w http.ResponseWriter, r *http.Request, params AuthCallbackParams) {
	var request AuthCallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthCallback(ctx, request.(AuthCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthCallbackResponseObject); ok {
		if err := validResponse.VisitAuthCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthLogin operation middleware
func (sh *strictHandler) AuthLogin(w http.ResponseWriter, r *http.Request) {
	var request AuthLoginRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthLogin(ctx, request.(AuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthLoginResponseObject); ok {
		if err := validResponse.VisitAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthLogout operation middleware
func (sh *strictHandler) AuthLogout(w http.ResponseWriter, r *http.Request) {
	var request AuthLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthLogout(ctx, request.(AuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthLogoutResponseObject); ok {
		if err := validResponse.VisitAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthMe operation middleware
func (sh *strictHandler) AuthMe(w http.ResponseWriter, r *http.Request) {
	var request AuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthMe(ctx, request.(AuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthMeResponseObject); ok {
		if err := validResponse.VisitAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
