// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github_app.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitHubAppInstallation = `-- name: DeleteGitHubAppInstallation :exec
DELETE FROM github_app_installations
WHERE installation_id = $1
`

func (q *Queries) DeleteGitHubAppInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubAppInstallation, installationID)
	return err
}

const getGitHubAppInstallationByAccountID = `-- name: GetGitHubAppInstallationByAccountID :one
SELECT id, installation_id, account_type, account_id, account_login, account_avatar_url, installer_user_id, suspended_at, created_at, updated_at FROM github_app_installations
WHERE account_id = $1
`

func (q *Queries) GetGitHubAppInstallationByAccountID(ctx context.Context, accountID int64) (GithubAppInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubAppInstallationByAccountID, accountID)
	var i GithubAppInstallation
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.AccountType,
		&i.AccountID,
		&i.AccountLogin,
		&i.AccountAvatarUrl,
		&i.InstallerUserID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubAppInstallationByID = `-- name: GetGitHubAppInstallationByID :one
SELECT id, installation_id, account_type, account_id, account_login, account_avatar_url, installer_user_id, suspended_at, created_at, updated_at FROM github_app_installations
WHERE installation_id = $1
`

func (q *Queries) GetGitHubAppInstallationByID(ctx context.Context, installationID int64) (GithubAppInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubAppInstallationByID, installationID)
	var i GithubAppInstallation
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.AccountType,
		&i.AccountID,
		&i.AccountLogin,
		&i.AccountAvatarUrl,
		&i.InstallerUserID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitHubAppInstallationsByAccountIDs = `-- name: ListGitHubAppInstallationsByAccountIDs :many
SELECT id, installation_id, account_type, account_id, account_login, account_avatar_url, installer_user_id, suspended_at, created_at, updated_at FROM github_app_installations
WHERE account_id = ANY($1::bigint[])
ORDER BY account_id
`

func (q *Queries) ListGitHubAppInstallationsByAccountIDs(ctx context.Context, accountIds []int64) ([]GithubAppInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubAppInstallationsByAccountIDs, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubAppInstallation
	for rows.Next() {
		var i GithubAppInstallation
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.AccountType,
			&i.AccountID,
			&i.AccountLogin,
			&i.AccountAvatarUrl,
			&i.InstallerUserID,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubAppInstallationsByUserID = `-- name: ListGitHubAppInstallationsByUserID :many
SELECT id, installation_id, account_type, account_id, account_login, account_avatar_url, installer_user_id, suspended_at, created_at, updated_at FROM github_app_installations
WHERE installer_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGitHubAppInstallationsByUserID(ctx context.Context, userID pgtype.UUID) ([]GithubAppInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubAppInstallationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubAppInstallation
	for rows.Next() {
		var i GithubAppInstallation
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.AccountType,
			&i.AccountID,
			&i.AccountLogin,
			&i.AccountAvatarUrl,
			&i.InstallerUserID,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubAppOrganizationInstallations = `-- name: ListGitHubAppOrganizationInstallations :many
SELECT id, installation_id, account_type, account_id, account_login, account_avatar_url, installer_user_id, suspended_at, created_at, updated_at FROM github_app_installations
WHERE account_type = 'organization'
ORDER BY account_login
`

func (q *Queries) ListGitHubAppOrganizationInstallations(ctx context.Context) ([]GithubAppInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubAppOrganizationInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubAppInstallation
	for rows.Next() {
		var i GithubAppInstallation
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.AccountType,
			&i.AccountID,
			&i.AccountLogin,
			&i.AccountAvatarUrl,
			&i.InstallerUserID,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitHubAppInstallationSuspended = `-- name: UpdateGitHubAppInstallationSuspended :exec
UPDATE github_app_installations
SET suspended_at = $1, updated_at = now()
WHERE installation_id = $2
`

type UpdateGitHubAppInstallationSuspendedParams struct {
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
	InstallationID int64              `json:"installation_id"`
}

func (q *Queries) UpdateGitHubAppInstallationSuspended(ctx context.Context, arg UpdateGitHubAppInstallationSuspendedParams) error {
	_, err := q.db.Exec(ctx, updateGitHubAppInstallationSuspended, arg.SuspendedAt, arg.InstallationID)
	return err
}

const upsertGitHubAppInstallation = `-- name: UpsertGitHubAppInstallation :exec
INSERT INTO github_app_installations (
    installation_id,
    account_type,
    account_id,
    account_login,
    account_avatar_url,
    installer_user_id,
    suspended_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    now(),
    now()
)
ON CONFLICT (installation_id) DO UPDATE SET
    account_type = EXCLUDED.account_type,
    account_login = EXCLUDED.account_login,
    account_avatar_url = EXCLUDED.account_avatar_url,
    suspended_at = EXCLUDED.suspended_at,
    updated_at = now()
`

type UpsertGitHubAppInstallationParams struct {
	InstallationID   int64              `json:"installation_id"`
	AccountType      GithubAccountType  `json:"account_type"`
	AccountID        int64              `json:"account_id"`
	AccountLogin     string             `json:"account_login"`
	AccountAvatarUrl pgtype.Text        `json:"account_avatar_url"`
	InstallerUserID  pgtype.UUID        `json:"installer_user_id"`
	SuspendedAt      pgtype.Timestamptz `json:"suspended_at"`
}

func (q *Queries) UpsertGitHubAppInstallation(ctx context.Context, arg UpsertGitHubAppInstallationParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubAppInstallation,
		arg.InstallationID,
		arg.AccountType,
		arg.AccountID,
		arg.AccountLogin,
		arg.AccountAvatarUrl,
		arg.InstallerUserID,
		arg.SuspendedAt,
	)
	return err
}
