// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisStatus string

const (
	AnalysisStatusPending   AnalysisStatus = "pending"
	AnalysisStatusRunning   AnalysisStatus = "running"
	AnalysisStatusCompleted AnalysisStatus = "completed"
	AnalysisStatusFailed    AnalysisStatus = "failed"
)

func (e *AnalysisStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalysisStatus(s)
	case string:
		*e = AnalysisStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalysisStatus: %T", src)
	}
	return nil
}

type NullAnalysisStatus struct {
	AnalysisStatus AnalysisStatus `json:"analysis_status"`
	Valid          bool           `json:"valid"` // Valid is true if AnalysisStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalysisStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnalysisStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalysisStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalysisStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalysisStatus), nil
}

type TestStatus string

const (
	TestStatusActive  TestStatus = "active"
	TestStatusSkipped TestStatus = "skipped"
	TestStatusTodo    TestStatus = "todo"
	TestStatusFocused TestStatus = "focused"
	TestStatusXfail   TestStatus = "xfail"
)

func (e *TestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestStatus(s)
	case string:
		*e = TestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestStatus: %T", src)
	}
	return nil
}

type NullTestStatus struct {
	TestStatus TestStatus `json:"test_status"`
	Valid      bool       `json:"valid"` // Valid is true if TestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestStatus), nil
}

type Analysis struct {
	ID           pgtype.UUID        `json:"id"`
	CodebaseID   pgtype.UUID        `json:"codebase_id"`
	CommitSha    string             `json:"commit_sha"`
	BranchName   pgtype.Text        `json:"branch_name"`
	Status       AnalysisStatus     `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TotalSuites  int32              `json:"total_suites"`
	TotalTests   int32              `json:"total_tests"`
}

type Codebasis struct {
	ID            pgtype.UUID        `json:"id"`
	Host          string             `json:"host"`
	Owner         string             `json:"owner"`
	Name          string             `json:"name"`
	DefaultBranch pgtype.Text        `json:"default_branch"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TestCase struct {
	ID         pgtype.UUID `json:"id"`
	SuiteID    pgtype.UUID `json:"suite_id"`
	Name       string      `json:"name"`
	LineNumber pgtype.Int4 `json:"line_number"`
	Status     TestStatus  `json:"status"`
	Tags       []byte      `json:"tags"`
	Modifier   pgtype.Text `json:"modifier"`
}

type TestSuite struct {
	ID         pgtype.UUID `json:"id"`
	AnalysisID pgtype.UUID `json:"analysis_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Name       string      `json:"name"`
	FilePath   string      `json:"file_path"`
	LineNumber pgtype.Int4 `json:"line_number"`
	Framework  pgtype.Text `json:"framework"`
	Depth      int32       `json:"depth"`
}
