// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: quota_reservation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuotaReservation = `-- name: CreateQuotaReservation :one
INSERT INTO quota_reservations (user_id, event_type, reserved_amount, job_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, event_type, reserved_amount, job_id, expires_at, created_at
`

type CreateQuotaReservationParams struct {
	UserID         pgtype.UUID    `json:"user_id"`
	EventType      UsageEventType `json:"event_type"`
	ReservedAmount int32          `json:"reserved_amount"`
	JobID          int64          `json:"job_id"`
}

func (q *Queries) CreateQuotaReservation(ctx context.Context, arg CreateQuotaReservationParams) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, createQuotaReservation,
		arg.UserID,
		arg.EventType,
		arg.ReservedAmount,
		arg.JobID,
	)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.ReservedAmount,
		&i.JobID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuotaReservationByJobID = `-- name: DeleteQuotaReservationByJobID :exec
DELETE FROM quota_reservations
WHERE job_id = $1
`

func (q *Queries) DeleteQuotaReservationByJobID(ctx context.Context, jobID int64) error {
	_, err := q.db.Exec(ctx, deleteQuotaReservationByJobID, jobID)
	return err
}

const getTotalReservedAmount = `-- name: GetTotalReservedAmount :one
SELECT
    COALESCE(SUM(reserved_amount), 0)::bigint AS total
FROM quota_reservations
WHERE user_id = $1
    AND event_type = $2
    AND expires_at > now()
`

type GetTotalReservedAmountParams struct {
	UserID    pgtype.UUID    `json:"user_id"`
	EventType UsageEventType `json:"event_type"`
}

func (q *Queries) GetTotalReservedAmount(ctx context.Context, arg GetTotalReservedAmountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalReservedAmount, arg.UserID, arg.EventType)
	var total int64
	err := row.Scan(&total)
	return total, err
}
