// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: river_job.sql

package db

import (
	"context"
)

const findActiveRiverJobByRepo = `-- name: FindActiveRiverJobByRepo :one
SELECT
    (args->>'commit_sha')::text as commit_sha,
    state::text as state
FROM river_job
WHERE
    kind = $1::text
    AND state IN ('available', 'pending', 'retryable', 'running', 'scheduled')
    AND args->>'owner' = $2::text
    AND args->>'repo' = $3::text
ORDER BY created_at DESC
LIMIT 1
`

type FindActiveRiverJobByRepoParams struct {
	Kind  string `json:"kind"`
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

type FindActiveRiverJobByRepoRow struct {
	CommitSha string `json:"commit_sha"`
	State     string `json:"state"`
}

func (q *Queries) FindActiveRiverJobByRepo(ctx context.Context, arg FindActiveRiverJobByRepoParams) (FindActiveRiverJobByRepoRow, error) {
	row := q.db.QueryRow(ctx, findActiveRiverJobByRepo, arg.Kind, arg.Owner, arg.Repo)
	var i FindActiveRiverJobByRepoRow
	err := row.Scan(&i.CommitSha, &i.State)
	return i, err
}
