// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: system_config.sql

package db

import (
	"context"
)

const getSystemConfigValue = `-- name: GetSystemConfigValue :one
SELECT value
FROM system_config
WHERE key = $1
`

func (q *Queries) GetSystemConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSystemConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
