// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMonthlyUsage = `-- name: GetMonthlyUsage :one
SELECT
    COALESCE(SUM(quota_amount), 0)::bigint AS total
FROM usage_events
WHERE user_id = $1
    AND event_type = $2
    AND created_at >= $3
    AND created_at < $4
`

type GetMonthlyUsageParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	EventType   UsageEventType     `json:"event_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetMonthlyUsage(ctx context.Context, arg GetMonthlyUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyUsage,
		arg.UserID,
		arg.EventType,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUsageByPeriod = `-- name: GetUsageByPeriod :many
SELECT
    event_type,
    COALESCE(SUM(quota_amount), 0)::bigint AS total
FROM usage_events
WHERE user_id = $1
    AND created_at >= $2
    AND created_at < $3
GROUP BY event_type
`

type GetUsageByPeriodParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetUsageByPeriodRow struct {
	EventType UsageEventType `json:"event_type"`
	Total     int64          `json:"total"`
}

func (q *Queries) GetUsageByPeriod(ctx context.Context, arg GetUsageByPeriodParams) ([]GetUsageByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getUsageByPeriod, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageByPeriodRow
	for rows.Next() {
		var i GetUsageByPeriodRow
		if err := rows.Scan(&i.EventType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
